[versions]
junit-jupiter = "5.10.2"

scala = "2.13.12"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
scala-library = { module = "org.scala-lang:scala-library", version.ref = "scala" }